parser: "@typescript-eslint/parser"

plugins:
  - "@typescript-eslint"

parserOptions:
  ecmaVersion: latest
  sourceType: "module"
  project: "tsconfig.json"

env:
  es2020: true
  browser: true

extends:
  "htmlacademy/vanilla"
